name: frieren
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - lame=3.100
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libunistring=0.9.10
  - libvpx=1.7.0
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.8.19
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - x264=1!157.20191217
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - audioread==3.0.1
      - babel==2.15.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - braceexpand==0.1.7
      - cachetools==5.3.3
      - cdpam==0.0.6
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clip==1.0
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==4.4.2
      - deepfilterlib==0.5.6
      - deepfilternet==0.5.6
      - defusedxml==0.7.1
      - diffusers==0.27.2
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - ffmpeg==1.4
      - filelock==3.13.4
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - future==1.0.0
      - fvcore==0.1.6
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.63.0
      - h11==0.14.0
      - h5py==3.11.0
      - hdbscan==0.8.39
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - idna==3.7
      - imageio==2.34.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipykernel==6.29.4
      - ipython==8.12.3
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - laion-clap==1.1.6
      - lazy-loader==0.4
      - librosa==0.9.1
      - lightning-utilities==0.11.2
      - llvmlite==0.41.1
      - loguru==0.7.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.0
      - mistune==3.0.2
      - mmcv==2.2.0
      - mmengine==0.10.4
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - noisereduce==3.0.3
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - numba==0.58.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - opencv-python==4.9.0.80
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pastel==0.2.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.3.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.1
      - poethepoet==0.10.0
      - pooch==1.8.1
      - portalocker==2.8.2
      - pretty-errors==1.2.25
      - proglog==0.1.10
      - progressbar==2.5
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==3.20.1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pudb==2024.1.2
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydeprecate==0.3.2
      - pydub==0.25.1
      - pyee==11.1.0
      - pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-ffmpeg==2.0.12
      - python-json-logger==2.0.7
      - pytorch-lightning==1.2.10
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2024.4.16
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - safetensors==0.4.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.5.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soupsieve==2.5
      - soxr==0.3.7
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - timm==1.0.15
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - tomlkit==0.13.0
      - torch==2.3.0
      - torchaudio==2.3.1
      - torchcde==0.2.5
      - torchdiffeq==0.2.4
      - torchdyn==1.0.6
      - torchlibrosa==0.1.0
      - torchmetrics==0.2.0
      - torchsde==0.2.6
      - torchvision==0.18.0
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.40.0
      - triton==2.3.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - urwid==2.6.15
      - urwid-readline==0.14
      - wandb==0.17.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webdataset==0.2.86
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - wget==3.2
      - widgetsnbextension==4.0.11
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.18.1